// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNJ7OLA4bW7fiSGIBO2KPRAdHyiE7L3U',
    appId: '1:374338598102:android:b61c93da562536ce210577',
    messagingSenderId: '374338598102',
    projectId: 'chatbyhridoy',
    storageBucket: 'chatbyhridoy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzQ9UTnRwX485ubH-qkWYqqoOWCg2lOhw',
    appId: '1:374338598102:ios:b474b4483f4a8b66210577',
    messagingSenderId: '374338598102',
    projectId: 'chatbyhridoy',
    storageBucket: 'chatbyhridoy.firebasestorage.app',
    iosBundleId: 'com.example.quickmassage',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgmfRMogzHoFfbkkdm9oA-UKCcoLw19a8',
    appId: '1:374338598102:web:762640c8864f301f210577',
    messagingSenderId: '374338598102',
    projectId: 'chatbyhridoy',
    authDomain: 'chatbyhridoy.firebaseapp.com',
    storageBucket: 'chatbyhridoy.firebasestorage.app',
    measurementId: 'G-8L9KGVEJXZ',
  );

}